### ISSUE TITLE
lock mysql version in docker

### ISSUE THREAD

**Issue by m1kesk** [fugasjunior/arma-server-manager#102]
currently, in docker you are using image for "mysql" without version ( default is latest ). Latest version can update with breaking changes (from version 5.6 to 7.x or 8.x ) and application will not work.

in docker-compose.yaml
change 
`image: mysql`
to
`image: mysql:8.3.0`

_note: latest tag version is currently 8.3.0 when creating this issue_

**Comment by fugasjunior** [comment]
Thank you for the suggestion. Change to docker-compose.yml is now integrated into dev branch, closing the issue.
