### ISSUE TITLE
steamProtocolMaxDataSize

### ISSUE THREAD

**Issue by domagojhack** [fugasjunior/arma-server-manager#129]
**Is your feature request related to a problem? Please describe.**

I am running a heavily moded server and parameter 'steamProtocolMaxDataSize' needs to be set so the server can tell the client about all the mods it has installed

**Describe the solution you'd like**

The settings window for the server should have a 'steamProtocolMaxDataSize' input window when editing settings for 'server.cfg'

**Describe alternatives you've considered**

Currently, I am hardcoding it inside the customized '.cfg' but if I change any other setting in the settings manager all my changes are rewritten.

**Comment by fugasjunior** [comment]
You should be able to put any additional options for the [server config file](https://community.bistudio.com/wiki/Arma_3:_Server_Config_File) into the "**Additional options**" field as long as they're not already present in the generated config. Could you give that a try and see whether it works?
