### ISSUE TITLE
Port editing / Multiple instances?

### ISSUE THREAD

**Issue by Ztrack** [fugasjunior/arma-server-manager#14]
How do you edit the port?
Is only one instance possible?

**Comment by fugasjunior** [comment]
Currently, the UI is designed only for running a single instance of the server. Once I have a bit more free time, I am planning to add support for multiple instances and also allow hosting newer Arma titles such as Reforger.

You can however edit the port in the "Settings" tab.

**Comment by fugasjunior** [comment]
Port editing and multiple instances have been added in version v1.0.0 which is now available
