### ISSUE TITLE
steamProtocolMaxDataSize settings

### ISSUE THREAD

**Issue by rhidenor** [fugasjunior/arma-server-manager#146]
I would like to ask you to implement the steamProtocolMaxDataSize setting in the web interface, if possible!
Currently I can enter it in the configuration file, but unfortunately when I press the "Submit" button in the admin interface, it is overwritten, so the steamProtocolMaxDataSize setting also disappears.

**Comment by fugasjunior** [comment]
You can use the "Additional options" field to fill out any [server options](https://community.bistudio.com/wiki/Arma_3:_Server_Config_File) which are not available in the interface.

Example:
<img width="467" alt="image" src="https://github.com/user-attachments/assets/a19f5def-befb-4100-a753-69003cb40e82">

**Comment by rhidenor** [comment]
Thx for your reply!

**Comment by fugasjunior** [comment]
No problem! Feel free to reopen the issue if this does not work for you.
