### ISSUE TITLE
admins parameter

### ISSUE THREAD

**Issue by rhidenor** [fugasjunior/arma-server-manager#147]
admins[] = { "<UID>" };

I would like to ask you to implement the admins[] = { "" }; setting in the web interface, if possible!
Currently I can enter it in the configuration file, but unfortunately pressing the "Submit" button in the admin interface overwrites it, so the admins[] = { "" }; setting also disappears.

**Comment by fugasjunior** [comment]
Same as #146, please try using the "Additional options" field.

**Comment by rhidenor** [comment]
Thx for your reply!
