### ISSUE TITLE
line 92: mapping key "volumes" already defined at line 46 when trying to spin up/start the panel !

### ISSUE THREAD

**Issue by OfficialMikeJ** [fugasjunior/arma-server-manager#152]
**Describe the bug**
When I go to run the Docker compose up or Docker compose up -d commands I get the following error:

"line 92: mapping key "volumes" already defined at line 46" without the quotes.

**To Reproduce**

Tried to find line 46 was not able to find it.

NANO into both "docker-compose.yml File & .env File.

Was not able to get the server to spin up in Docker.

**Expected behavior**
Was expecting the server to spin up right away after creating and saving the docker-compose.yml & .env files.
**Screenshots**
N/A
**Environment**
**OS**: Ubuntu 20.04-LTS

**docker-compose.yml**
No Modifications have been done to the docker-compose.yml file.

**.env**
Would not allow me to copy any of the contents from my .env file.

**Logs**
If relevant, include the application logs (`docker logs`) or RPT logs of the game server.

**Additional context**
Nothing elese I can share or show.

**Comment by fugasjunior** [comment]
Please share the `.env` file (removing any sensitive data). It's possible it's misconfigured somehow.

**Comment by OfficialMikeJ** [comment]
Hello, I have figured out my issue. I didn't place the .env & docker-compose.yml files inside the "home/steam/amraservermanager" directory. All is good now. thank you for this awesome tool. Mike.
