### ISSUE TITLE
How to import mod presets?

### ISSUE THREAD

**Issue by SirSKillz** [fugasjunior/arma-server-manager#40]
If I export a mod preset from Arma 3, how would I go about importing that preset into the server? If that is not a feature, is that something that is planned?

**Comment by fugasjunior** [comment]
Hi, sorry for taking so long to respond to this issue.

Currently, there's no way to import or export mod presets in the GUI. However, I'm planning to add support for this in the form of the standard HTML file and perhaps also simpler CSV file.

**Comment by fugasjunior** [comment]
The ability to import and export launcher HTML preset files has been merged to `dev` branch and it'll be a part of the next release v1.1.0.
