### ISSUE TITLE
Downloading mods gives a "Generic" error.

### ISSUE THREAD

**Issue by swebow** [fugasjunior/arma-server-manager#46]
Hi!

I try to download mods. I always get a "generic" error.
I use an "empty" account with no Arma 3 game installed, but with a valid API key.
I use a empty account after recommendations from Bohemia Interactive to have a dedicated server account.

I'll uploaded the errors in a .txt
[log.txt](https://github.com/fugasjunior/arma-server-manager/files/10609190/log.txt)

**Comment by fugasjunior** [comment]
Hi,

sometimes the underlying SteamCMD which handles mod downloads is not entirely reliable and might take a couple of tries to actually finish installing the mod. This applies especially to large mods, such as CUP Terrains which you're installing.

From the log files, I see that you uninstalled the mod after failure before retrying. When a download fails, I'd rather recommend trying to update it without uninstalling. Just select the mods that failed to install and click the update icon. It might take a couple of tries, but eventually should finish successfully.

**Comment by swebow** [comment]
Solved it. I needed Arma 3 on the account. So the Bohemia Wiki isn't fully up to date.
