### ISSUE TITLE
Having problems downloading some mods

### ISSUE THREAD

**Issue by lapochka8** [fugasjunior/arma-server-manager#65]
Im new to all of this, but when I attempt to install some mods, I get hit with an error where it says "
Installation of some mods failed. Review the errors below:

Unidentified error. Please contact the system administrator."

When i try to look for the error, i go into the logs of the specific directory I have it downloading mods to. Im having a rough go at it. Any advice or a walkthrough would be appreciated.

**Comment by fugasjunior** [comment]
Hi, first of all, sorry for the delay, I didn't have enough time to work on this project in the past couple of weeks.

Regarding your problem, the issue could be described in the application logs. Are you running the application in Docker or natively?

**Comment by wheelyjoe** [comment]
I am also having this issuse - Using Docker

**Comment by fugasjunior** [comment]
> I am also having this issuse - Using Docker

Can you share the application logs? You can get them by executing command ```docker logs arma-server-manager-armaservermanager-1```.

Also, make sure you're running the latest version of the image (v1.1.1). There was an issue #69 which broke SteamCMD downloads, which is fixed in the current version.

To make sure you're on the latest version, run the following:
```
docker compose pull
docker compose up -d
```

**Comment by wheelyjoe** [comment]
![image](https://github.com/fugasjunior/arma-server-manager/assets/49379818/18407ef4-b73c-43ad-9b50-59da5466c66a)


Have updated though - I did only just set it up today so it should be the latest. Booting agian

**Comment by fugasjunior** [comment]
Thanks for the info, glad it's fixed. 

Regarding the 2FA, if you use the mobile authenticator app, then this is currently unsupported as the token only lasts for a few seconds. If you only use tokens sent via email, then the token lasts for a couple of days/weeks, so it can be persisted in the application and used repeatedly.

**Comment by wheelyjoe** [comment]
Ahhhhh yeah it's the app. Can you use email if you have the app, as an option?

Top stuff mate, thanks.

**Comment by fugasjunior** [comment]
You can still configure to use just the email tokens even when using the mobile app. Just go to Steam settings -> Security -> under Steam Guard, click Manage Steam Guard. There you can pick "Get Steam Guard codes by email"
