### ISSUE TITLE
Uploading multiple files

### ISSUE THREAD

**Issue by odyn666** [fugasjunior/arma-server-manager#67]
currently i uploading over 40 scenarios one by one can you add option for uploading multiple file at once ? # #

**Comment by fugasjunior** [comment]
The ability to upload multiple scenarios at once is currently released as part of [v1.1.2-beta](https://github.com/fugasjunior/arma-server-manager/releases/tag/v1.1.2-beta) and should soon get to a stable release.

**Comment by fugasjunior** [comment]
Released in v1.2.0.
