### ISSUE TITLE
Cannot configure launch parameters 

### ISSUE THREAD

**Issue by armed503** [fugasjunior/arma-server-manager#73]
Unable to find a way to edit launch parameters such as auto init for Arma 3.

**Comment by armed503** [comment]
> Currently, there isn't any way to specify launch properties for any server through the manager as there weren't any use cases for this yet. Are there any other launch parameters besides -autoinit you'd like to edit? I might either put some options to the UI or at least add the ability to specify custom launch parameters in the application.properties or .env file.

-autoinit is most important but being able to add/remove startup parameters as needed would be preferred. If you add a section just like you do for the "Additional" section for the server.cfg that could work as well.

**Comment by WatskeBart** [comment]
> > Currently, there isn't any way to specify launch properties for any server through the manager as there weren't any use cases for this yet. Are there any other launch parameters besides -autoinit you'd like to edit? I might either put some options to the UI or at least add the ability to specify custom launch parameters in the application.properties or .env file.
> 
> -autoinit is most important but being able to add/remove startup parameters as needed would be preferred. If you add a section just like you do for the "Additional" section for the server.cfg that could work as well.

Additional section would be great. I'd like to use the parameters `-limitFPS` and `-bandwidthAlg` also

**Comment by fugasjunior** [comment]
The ability to customize launch parameters is currently released as part of [v1.1.2-beta](https://github.com/fugasjunior/arma-server-manager/releases/tag/v1.1.2-beta) and should soon get to a stable release.

**Comment by fugasjunior** [comment]
Custom launch parameters are now released in v1.2.0.
