### ISSUE TITLE
network_mode not available on windows

### ISSUE THREAD

**Issue by NikTink** [fugasjunior/arma-server-manager#78]
Which ports are necessary to be setup manually? ~~I cannot access the tomcat(?) service from a browser~~

**Comment by NikTink** [comment]
Adminer correctly exposed on port 8090 (from the docker compose file)

**Comment by NikTink** [comment]
As soon as i remove "network_mode", armaservermanager cant connect to sql

**Comment by fugasjunior** [comment]
Hi, sorry about taking this long to respond. 

The manager web UI runs on port 8080, so you need to expose that. In addition, you need to expose all ports which the servers you'll be running require. For example, default Arma 3 server would require at least ports 2302/udp and 2303/udp to be open. However, if you need BattlEye to work, there are additional ports which you need to open. You can refer to [official documentation](https://community.bistudio.com/wiki/Arma_3:_Dedicated_Server#Port_Forwarding).

When you remove host network mode, you also need to change the database URL in your .env file to `jdbc:mysql://db:3306/armaservermanager_db`.
