### ISSUE TITLE
DayZ missing from webmanager.

### ISSUE THREAD

**Issue by lapochka8** [fugasjunior/arma-server-manager#79]

**Comment by lapochka8** [comment]
Went back to V1.0, still missing

**Comment by fugasjunior** [comment]
Hi, unfortunately there is no official DayZ (non-experimental) dedicated server for Linux. That means when you either use the web manager natively on Linux host or use the Docker setup (as the image is based on Linux), non-experimental DayZ server will not be available.

Currently, the only way to be able to manage DayZ server is to install the manager natively on a Windows host by following [Custom installation (no Docker)](https://github.com/fugasjunior/arma-server-manager#custom-installation-no-docker) guide.
