### ISSUE TITLE
Custom Difficulty Settings Not being applied

### ISSUE THREAD

**Issue by danielth-uk** [fugasjunior/arma-server-manager#80]
I have setup arma-server-manager on my Linux box and was using it for some testing, but one thing I noticed is that all of the settings that I have set have not been applied. 

![image](https://github.com/fugasjunior/arma-server-manager/assets/73545698/f9560547-a7f2-4695-8138-a96b2dd0434f)
![image](https://github.com/fugasjunior/arma-server-manager/assets/73545698/24b8562f-a22d-4a3e-b6f8-5620923a1561)
![image](https://github.com/fugasjunior/arma-server-manager/assets/73545698/c8da66e6-6961-4dad-84ce-8ddb1ad64978)

The data seems to be in the database, so it has saved, not sure why it hasn't applied. Any ideas?

**Comment by fugasjunior** [comment]
Hi, can you please clarify the problem? Are the difficulty settings not being applied in game, or are you unable to see them in the UI?

You should be able to find the custom difficulty in a generated file `ARMA3_{server id}.Arma3Profile` somewhere in `/home/steam/armaservermanager/servers/ARMA3/custom_profiles`. Can you check the file if the values there are set up correctly?

**Comment by danielth-uk** [comment]
Hi, sorry. So the values are being saved to the `ARMA3_{server id}.Arma3Profile` and are correct but they are not being applied in-game, for example, in the arma-server-manager UI I can turn off third-person, and start the server, however, third-person is still on. I did a bit of research, could it possibly be because of this?
![image](https://github.com/fugasjunior/arma-server-manager/assets/73545698/38afc307-6356-4323-8fa7-14aab7968040)
[here](https://community.bistudio.com/wiki/Arma_3:_Dedicated_Server)

**Comment by fugasjunior** [comment]
Thanks for the clarification! Just to be sure, did you select Custom difficulty in game when starting the mission? It can also be forced by adding `forcedDifficulty = "Custom";` to additional settings if needed.

**Comment by fugasjunior** [comment]
You should be able to see the difficulty selection screen when starting the mission, see the screenshot: 
![image](https://github.com/fugasjunior/arma-server-manager/assets/17858781/49e84276-2a36-4f36-b2b0-1a85e41ac3d0)

You need to select "Custom" for the settings from the UI to apply in game. `forcedDifficulty = "Custom"` in additional settings should force this difficulty. I've just tested that the difficulty applies correctly.

If it still doesn't work for you, there might be something wrong with your concrete environment. In that case, could you please provide further info so I can try to reproduce this issue? Such as whether you're running natively or in Docker, how does the Arma3Profile file look etc.

**Comment by fugasjunior** [comment]
No problem, glad it's working, thanks for the info!
