### ISSUE TITLE
Feature request: Ability to schedule Arma server automatic restart

### ISSUE THREAD

**Issue by adevries17** [fugasjunior/arma-server-manager#84]
First, I'd like to say, I love this project, it is awesome, great work!

Second, I'd like the ability to schedule an automatic restart of the Arma3 server that I am running. If this already exists, then I haven't been able to find it. Sure, this could probably done with a cron job in the container, and a shell script, but I'm not fully sure on how that would integrate with the rest of the application.

**Comment by fugasjunior** [comment]
Scheduling automatic restarts is now available in v1.2.0.
