### ISSUE TITLE
Installation keeps running with no progress.

### ISSUE THREAD

**Issue by ZeakDK** [fugasjunior/arma-server-manager#85]
Sorry, I'm really new to docker, so forgive noob questions.

I installed it with docker compose running on Unraid. I can get the web interface up and running, but as soon as I launched it, both Arma 3 and Arma Reforger was installing. It just says "Installing" and then the bar beneath them are cycling through, but nothing happens. I left it running for an hour, just to make sure, but nothing happens.

I'm a little unsure about what logs you need and how to get them.

**Comment by CubelightCodes** [comment]
You can list your containers with `docker ps` to see your Containers with ID's and see error logs with `docker compose logs CONTAINER_ID_HERE`. Maybe that help

**Comment by fugasjunior** [comment]
Hi, this is likely not a problem with Docker, but with the manager itself. This problem can happen when you start the installation of a server and shut the manager down (or if it crashes) during the installation. I'm working on a fix for this problem, but in the meantime, there are two possible fixes you can do.

1. Manually change server installation status in database. You can use Adminer which is included in the docker-compose file (running at http://localhost:8090 by default) to access the database. Use MySQL user, DB and password as set in the `.env` file. There, select "SQL command" and execute the following query:
```sql
UPDATE server_installation SET installation_status = 'ERROR' WHERE installation_status = 'INSTALLATION_IN_PROGRESS'
```
After that, you should be able to retry the installation of the server.

2. If you don't want to deal with manually changing data in the database, you can recreate the whole database altogether. This depends on how you set up the MySQL container, but should likely consist of the following steps:
  a) `docker compose down` to shut down the application
  b) `docker volume ls` to find the IDs of volumes which are associated with the MySQL database image. It should be something like `arma-server-manager_armaservermanager-db`.
  c) `docker volume rm <ID>` to remove the volume containing the database
  d) `docker compose up -d`
after doing so, try setting the steam authentication info and installing the server again.

**Comment by ZeakDK** [comment]
Thank you, that fixed it. I used method one.
