### ISSUE TITLE
Problems downloading unlisted mods

### ISSUE THREAD

**Issue by diaverso** [fugasjunior/arma-server-manager#96]
Problem with downloading mods that your status is: 
Current visibility: Unlisted 

If you download, any mod that is in the workshop as pubilico, it downloads and installs without problems.
But, when you try to add an unlisted one, it does not download them and displays the error.
"The mod is not consumed by any supported game."

https://i.imgur.com/FSlyOgK.png

I attach the 2 links I used:
Listing: https://steamcommunity.com/sharedfiles/filedetails/?id=3116102079
Unlisted: https://steamcommunity.com/sharedfiles/filedetails/?id=3090047341

Also, could you add an option to upload mods manually?

Thanks and best regards.

**Comment by fugasjunior** [comment]
Released in version 1.3.0.
