### ISSUE TITLE
tacticalPing settings

### ISSUE THREAD

**Issue by m1kesk** [fugasjunior/arma-server-manager#99]
according to wiki [https://community.bistudio.com/wiki/Arma_3:_Difficulty_Settings](https://community.bistudio.com/wiki/Arma_3:_Difficulty_Settings)
tactical ping ( Allows players to highlight a position via a Tactical Ping ) have these settings
0 = disabled, 
1 = in 3D scene
2 = on map
3 = both	Allows players to highlight a position via a Tactical Ping. 

please change UI to be able to select tacticalPing value from 0, 1, 2, 3

currently we can only change it to values 0 and 1

**Comment by fugasjunior** [comment]
Released in version 1.3.0.
